export const channels = {
  compileExplorerProgram: "explorer:compile-program",
  checkForUpdate: "app:check-for-update",
  getOpenCodeInfo: "opencode:get-info",
  openCodeStartupProgress: "opencode:startup-progress",
  getDoNotTrack: "app:get-do-not-track",
  getVersion: "app:get-version",
  installUpdate: "app:install-update",
  invokeExplorerProgram: "explorer:invoke-program",
  loadConfig: "config:load",
  openUrl: "app:open-url",
  patchConfig: "config:patch",
  relaunch: "app:relaunch",
  discoverStudioTargets: "studio-target:discover",
  installStudioTargetPrograms: "studio-target:install-programs",
  selectStudioTarget: "studio-target:select",
} as const;
